server:
  port: 9528

spring:
  application:
    name: cloudalibaba-sentinel-gateway #sentinel+gateway整合case
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置nacos地址
    gateway:
      routes:
        - id: pay_routh1
          uri: http://localhost:9001
          predicates:
            - Path=/pay/**